[CON-208] feat: Added the provider guides for the kit connector
amp-labs/docs pull request #102
Opened 2024-12-09 11:38 UTC by sanjay-a01

2024-12-12 16:10 UTC, RajatPawar requested changes
Minor changes, great work on the GIFs! Can you also run this through ChatGPT to make sure any grammatical errors are fixed, and to rephrase all sentences in a manner appropriate for a technical document?

2024-12-12 16:10 UTC, RajatPawar commented on src/images/provider-guides/kit_configure.gif
This GIF has the client secret visible in plaintext, which is not something we want to endorse. Can you please record this again without the secret showing? Thanks! I'd not show the secret in any gifs

2024-12-12 16:10 UTC, RajatPawar commented on src/provider-guides/kit.mdx
> +Here's how you can sign up for an Kit account:
Same as the other PR, let's skip this section

2024-12-12 16:10 UTC, RajatPawar commented on src/provider-guides/kit.mdx
> +### Creating an Kit App
Can you fix all occurrences of `an Kit` to `a Kit`?

2024-12-12 16:10 UTC, RajatPawar commented on src/provider-guides/kit.mdx
> +2. Click **Profile** icon, then click on **Settings** and go to the **Developer** in settings.
```suggestion
2. Click **Profile** icon, then click on **Settings** and go to **Developer**
```

2024-12-12 16:10 UTC, RajatPawar commented on src/provider-guides/kit.mdx
> +3. Click **Create a new app**.
```suggestion
3. Click on **Create a new app**.
```

2024-12-12 16:10 UTC, RajatPawar commented on src/provider-guides/kit.mdx
> +5. You can also add the below section
```suggestion
5. You can also add -
```

2024-12-12 16:10 UTC, RajatPawar commented on src/provider-guides/kit.mdx
> +5. Click **Save**. Then Click **Configure**.
```suggestion
5. Click **Save**. Next, you will need to **Configure** the app.
```

2024-12-12 16:10 UTC, RajatPawar commented on src/provider-guides/kit.mdx
> +6. Enter the Authorization URL: `https://app.kit.com/oauth/authorize` in the **Authorization URL** section.
Does kit need us to give the OAuth URL?

2024-12-12 16:10 UTC, RajatPawar commented on src/provider-guides/kit.mdx
> +6. Click **Save Changes**.
```suggestion
```

2024-12-13 07:33 UTC, sanjay-a01 commented on src/provider-guides/kit.mdx
> +6. Enter the Authorization URL: `https://app.kit.com/oauth/authorize` in the **Authorization URL** section.
Yeah! we need to give OAuth URL.

2024-12-20 08:11 UTC, RajatPawar approved these changes

2024-12-20 08:11 UTC, RajatPawar commented on src/provider-guides/kit.mdx
> +7. Enter the Redirect URIs: `https://api.withampersand.com/callbacks/v1/oauth` in the **Redirect URIs** section.
```suggestion
7. Enter `https://api.withampersand.com/callbacks/v1/oauth` in the **Redirect URIs** section.
```

2024-12-20 08:12 UTC, merged