[CON-548] feat: Added the provider guide for Sellsy Connector
amp-labs/docs pull request #104
Opened 2024-12-09 13:17 UTC by sanjay-a01

2024-12-12 16:04 UTC, RajatPawar requested changes
Nice! Couple of minor changes required. After you are done, can you please make sure that all text in this guide has the words `a Sellsy ..` and not `an Sellsy`? Also, I'd suggest running this entire text through something like ChatGPT to fix grammatical errors / phrasing errors which should be the cherry on the top :)

2024-12-12 16:04 UTC, RajatPawar commented on src/provider-guides/sellsy.mdx
> +4. Enter the **Access name** for the Creating an API Access.
What does this mean?

2024-12-12 16:04 UTC, RajatPawar commented on src/provider-guides/sellsy.mdx
> +7. Click **Save**.
```suggestion
7. Make sure to click on **Save**.
```

2024-12-12 16:04 UTC, RajatPawar commented on src/provider-guides/sellsy.mdx
> +2. Select the project where you want to create an Sellsy integration.
```suggestion
2. Select the project in which you want to create a Sellsy integration.
```

2024-12-12 16:04 UTC, RajatPawar commented on src/provider-guides/sellsy.mdx
> +6. Click **Save Changes**.
```suggestion
```

2024-12-16 12:17 UTC, sanjay-a01 commented on src/provider-guides/sellsy.mdx
> +4. Enter the **Access name** for the Creating an API Access.
In the second version of the API, they switched to OAuth 2.0 for authentication. When creating an OAuth application, there will be an option named API V2 (beta).

![image](https://github.com/user-attachments/assets/02db1d4e-dd49-4da8-a075-9bf07c031cf7)

2024-12-20 11:43 UTC, RajatPawar approved these changes

2024-12-20 11:43 UTC, RajatPawar commented on src/provider-guides/sellsy.mdx
> +3. Click the **API V2 (beta)** tab, then click **Create API Access** and select your **API access type**: Private.
```suggestion
3. Click the **API V2 (beta)** tab, then click **Create API Access** and select the **API access type** as *Private*.
```

2024-12-20 11:43 UTC, RajatPawar commented on src/provider-guides/sellsy.mdx
> +2. Select the project you want to create a Sellsy integration.
```suggestion
2. Select the project you want to create a Sellsy integration in.
```

2024-12-20 11:43 UTC, RajatPawar commented on src/provider-guides/sellsy.mdx
> +4. Enter the **Access name** for an API Access.
```suggestion
4. Enter your application's name as the **Access name**.
```

2024-12-20 11:48 UTC, merged