[ENG-1721] docs: add migration v2 embeddable ui components faq
amp-labs/docs pull request #112
Opened 2024-12-17 07:38 UTC by dionlow

### Summary
adds faq section for embeddable ui components

2024-12-17 23:49 UTC, laurenzlong requested changes

2024-12-17 23:49 UTC, laurenzlong commented on src/embeddable-ui-components.mdx
> +#### Why does my app loading no longer show when I use @amp-labs/react v2.x.
I'm pretty confused by this sentence.

2024-12-18 02:24 UTC, dionlow commented on src/embeddable-ui-components.mdx
> +#### Why does my app loading no longer show when I use @amp-labs/react v2.x.
```suggestion
#### Why does does styling break when migrating to @amp-labs/react v2?
```

2024-12-20 22:58 UTC, laurenzlong approved these changes

2024-12-20 22:58 UTC, merged