Supported Objects: Gong
amp-labs/docs pull request #57
Opened 2024-08-23 17:23 UTC by Cobalt0s

2024-08-24 14:15 UTC, laurenzlong commented
Leaving this PR unmerged for now since we haven't actually shipped the Gong connector yet.

2024-10-03 21:22 UTC, Cobalt0s commented
@laurenzlong last deep connector PR for Gong was merged.
I have added Write support for `calls` and incremental read for calls, which is reflected in updated docs. Let me know when this PR can be merged.

2024-10-04 23:16 UTC, laurenzlong requested changes

2024-10-04 23:16 UTC, laurenzlong commented on src/provider-guides/gong.mdx
>  - [Proxy Actions](/define-integrations/proxy-actions), using the base URL `https://api.gong.io`.
Can you revise this list to add Read Actions and Write Actions?

2024-10-07 17:26 UTC, Cobalt0s commented on src/provider-guides/gong.mdx
>  - [Proxy Actions](/define-integrations/proxy-actions), using the base URL `https://api.gong.io`.
Addressed.

I created the series of Gong PRs across repositories, where this one will be merged last. I feel positive about Gong.

2024-10-10 23:31 UTC, laurenzlong approved these changes

2024-10-10 23:31 UTC, laurenzlong commented on src/provider-guides/gong.mdx
> +Writing is supported for `Calls`, allowing submitting calls for AI processing.
```suggestion
Writing is supported for Calls.
```

2024-10-14 22:13 UTC, merged

2024-10-14 22:14 UTC, laurenzlong commented
merging this since Gong deep connector has been shipped in https://github.com/amp-labs/connectors/pull/1064