Supported Objects: DynamicsCRM
amp-labs/docs pull request #58
Opened 2024-08-23 17:43 UTC by Cobalt0s

2024-08-24 14:06 UTC, laurenzlong requested changes
1. Can you rebase from main? Since this guide has been updated recently

2. Supported Objects should be under "Supported Actions", and "What's Supported" heading should not be deleted

3. Can you list out a few (under 10) of the most common/useful objects? For those objects, can you also add links to the readable and writable columns? That will be useful for the builders to know. e.g. 
```
The Microsoft's DynamicsCRM connector supports reading from and writing to all the available objects in the Microsoft Dynamics 365 Sales module, which totals to more than 1000 objects and include:
- Contact ([writable fields](https://learn.microsoft.com/en-us/dynamics365/sales/developer/entities/contact#writable-columnsattributes), [read-only fields](https://learn.microsoft.com/en-us/dynamics365/sales/developer/entities/contact#read-only-columnsattributes))
- ...
- All the other objects in the [Dynamics Sales tables reference](https://learn.microsoft.com/en-us/dynamics365/sales/developer/about-entity-reference)
```

4. Is it actually important for the user to know that the data is served from Dataverse? I'm afraid linking to it might add more confusion than anything - what are they supposed to do with that information? They don't actually need to know about Dataverse in order to use the connector.

2024-08-25 13:38 UTC, Cobalt0s commented
> 1. You should actually be updating `dynamicsCRM.mdx`, not `microsoft.mdx`, they're different connectors.
> 2. Supported Objects should be under "Supported Actions", and "What's Supported" heading should not be deleted
> 3. Can you list out a few (under 10) of the most common/useful objects? For those objects, can you also add links to the readable and writable columns? That will be useful for the builders to know. e.g.
> 
> ```
> The Microsoft's DynamicsCRM connector supports reading from and writing to all the available objects in the Microsoft Dynamics 365 Sales module, which totals to more than 1000 objects and include:
> - Contact ([writable fields](https://learn.microsoft.com/en-us/dynamics365/sales/developer/entities/contact#writable-columnsattributes), [read-only fields](https://learn.microsoft.com/en-us/dynamics365/sales/developer/entities/contact#read-only-columnsattributes))
> - ...
> - All the other objects in the [Dynamics Sales tables reference](https://learn.microsoft.com/en-us/dynamics365/sales/developer/about-entity-reference)
> ```
> 
> 4. Is it actually important for the user to know that the data is served from Dataverse? I'm afraid linking to it might add more confusion than anything - what are they supposed to do with that information? They don't actually need to know about Dataverse in order to use the connector.

There is no such file as dynamicsCRM, hence I added it to microsoft. I thought it is similiar to how you structured Atlassian vs Jira relationship.

2024-08-25 14:10 UTC, Cobalt0s commented
@laurenzlong 
Speaking of dataverse. I like to mention it as the data that we provide comes from it. Which means whatever permissions people will setup will allow those object to be accessible using this connector.
Maybe I shouldve done other Microsoft Dataverse products to better understand and describe what this connector will allow people to do.
As I understand any Power Apps that you will design in their editor, its data can be accessed via DynamicsCRM too.

2024-08-27 11:32 UTC, laurenzlong approved these changes

2024-08-27 11:33 UTC, merged