update supported objects marketo connector
amp-labs/docs pull request #59
Opened 2024-08-23 22:37 UTC by Jkarage

2024-08-24 13:45 UTC, laurenzlong commented on src/provider-guides/marketo.mdx
> +- [Campaigns](https://developer.adobe.com/marketo-apis/api/mapi/#tag/Campaigns/operation/getCampaignsUsingGET)
@Jkarage I'm a bit confused - are all the listed objects a part of the Leads module? Or are some of them a part of the Assets module? Does the Assets module support anything yet? If not, then we shouldn't mention it.

2024-08-24 15:01 UTC, Jkarage commented on src/provider-guides/marketo.mdx
> +- [Campaigns](https://developer.adobe.com/marketo-apis/api/mapi/#tag/Campaigns/operation/getCampaignsUsingGET)
@laurenzlong  All of the listed are leads objects.I haven't added the supported Assets objects on the list as a client currently can not change module, And the default is Leads. So the listed are all Leads Objects.

2024-08-27 10:01 UTC, Jkarage commented on src/provider-guides/marketo.mdx
> +- [Campaigns](https://developer.adobe.com/marketo-apis/api/mapi/#tag/Campaigns/operation/getCampaignsUsingGET)
But we do have supported Assets Objects as well. Adding them.

2024-08-27 11:43 UTC, laurenzlong commented on src/provider-guides/marketo.mdx
> +- [Read Actions](/define-integrations/read-actions), including full historic backfill. Please note that incremental read is only supported for Email, Programs, SmartCampaigs and SmartLists. For other
Typo: SmartCampaigns should be SmartCampaigns

2024-08-27 11:43 UTC, laurenzlong commented on src/provider-guides/marketo.mdx
> +- [Campaigns](https://developer.adobe.com/marketo-apis/api/mapi/#tag/Campaigns/operation/getCampaignsUsingGET)
@Jkarage sorry, I was just asking a clarifying question - I didn't mean that you should add the Assets objects, since you're right it's pointless to add them to our docs because the user cannot change modules. Can you also remove the "Supported Modules" section and remove any mention of the Assets module? I don't want to cause any confusion.

2024-09-18 22:12 UTC, laurenzlong requested changes
@Jkarage sorry for the delay! I was out of office, I added some more comments.

2024-09-18 22:12 UTC, laurenzlong commented on src/provider-guides/marketo.mdx
> +The Marketo connector support writing in the following objects:
Can the connector also read from these objects? If so, then this sentence should be revised to:
`The Marketo connector support reading from and writing to the following objects:`

2024-09-18 22:12 UTC, laurenzlong commented on src/provider-guides/marketo.mdx
> +- [Read Actions](/define-integrations/read-actions), including full historic backfill. Please note that incremental read is only supported for Email, Programs, SmartCampaigns and SmartLists. For othe
I'm confused by the part that says "Please note that incremental read is only supported for Email, Programs, SmartCampaigns and SmartLists."
- Emails and Programs does not appear in the lists below at all, did you forget to add them?
- Are SmartCampaigns and SmartLists the same as the "Campaigns" and "Lists" below? If so, can you revise this sentence to say "Campaigns and Lists" instead so the terminology matches?

2024-09-19 06:24 UTC, Jkarage commented on src/provider-guides/marketo.mdx
> +The Marketo connector support writing in the following objects:
We can only perform Read operation with these objects.

2024-09-19 06:30 UTC, Jkarage commented on src/provider-guides/marketo.mdx
> +The Marketo connector support writing in the following objects:
We can only perform Write Operation with these Objects.

2024-09-19 06:45 UTC, Jkarage commented on src/provider-guides/marketo.mdx
> +- [Read Actions](/define-integrations/read-actions), including full historic backfill. Please note that incremental read is only supported for Email, Programs, SmartCampaigns and SmartLists. For othe
All these `Email, Programs, SmartCampaigns and SmartLists` are objects within Assets Module. That's the reason they are not listed below. Updating this to show that there is no Incremental Read support, as no object in the Leads Module supports it. I should have updated this when you said we should remove all Assets related objects in the doc for now.

2024-09-20 20:34 UTC, laurenzlong approved these changes

2024-09-20 20:34 UTC, merged