Commands Documentation
amp-labs/docs pull request #77
Opened 2024-10-16 15:35 UTC by renukashiwakoti

- Updated CLI overview section
- Added Commands reference section

2024-10-18 04:54 UTC, RajatPawar requested changes

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +- `-p, --project string`: Specifies the Ampersand project name or ID. Many commands require a project context, and this flag allows you to set it without needing to include it in each individual comm
Users do technically have to include the project for each command where it's needed, so I would skip this and just limit it to ` Specifies the Ampersand project name or ID.`. Optionally, we could add a line about how they can collect the project ID/name instead.

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +Logs into your Ampersand account via CLI.
Can this be more specific? Like `Authenticates you against the CLI via an interactive browser flow.`

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +  amp logout [--debug]
```suggestion
  amp logout
```

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +  amp logout [--debug]
Even though it's technically still valid, not something users would generally choose to do

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +## Integration Management Commands
```suggestion
## Managing integrations 
```

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +Deploys changes to integrations by uploading and applying your integration configurations.
```suggestion
Deploys the integrations defined in the `amp.yaml` file to Ampersand. If an integration already exists, this command will apply any changes to the existing integration.
```

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +- Use this command when you've made changes to your integration and want to update it in Ampersand.
This command also lets you deploy fresh integrations

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +- Removes the entire integration configuration from your project.
```suggestion
- Removes the integration & any associated installations from your project.
```

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +- Useful for managing multiple installations of the same integration.
```suggestion
```

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +amp deploy ./my-integration --project=my-project
```suggestion
amp deploy ./integrations --project=my-project
```

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +amp delete:integration abc123 --project=my-project
Instead of `abc123`, can you please add a dummy UUID?

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +amp delete:installation xyz789 --project=my-project
1) amp delete:installation requires an integration ID and an installation ID
2) Same as before, please add a dummy UUID

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +Lists all available destinations for integrations in your project.
```suggestion
Lists all available destinations in your project.
```

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +Lists all available destinations for integrations in your project.
Please add a ref to https://docs.withampersand.com/destinations here

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +- Useful for seeing where you can deploy your integrations.
```suggestion
```

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +Displays all current installations of integrations in your project.
```suggestion
Displays all current installations of a given integration in your project.
```

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +amp list:installations --project=<id-or-name> [--key=<api-key>] [--debug]
The usage needs `integrationId`

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +- Shows installation IDs, associated integration names, and their status.
```suggestion
```

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +amp list:installations --project=my-project
Needs fixing

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +- Includes integration IDs, names, and current versions.
```suggestion
```

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +- Includes integration IDs, names, and current versions.
Best to remove these because (1) is self explanatory, and we might add or remove fields in the response, so (2) could quickly get out of date

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +- Helpful for managing multiple projects or selecting a project for other commands.
This doesn't allow selecting another project, just lists it (selecting could mean an interactive selection to a user)

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +- Use `amp help` for general help and `amp help [command]` for command-specific help.
Can you move this up to the command definition? Help can display information about all commands / specific commands

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/command-reference.mdx
> +- Useful for verifying your installation or checking if updates are available.
```suggestion
- Useful for verifying your CLI version or checking if updates are available.
```

Installation in this context might be confusing

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/overview.mdx
> +2. Download the appropriate binary for your machine’s architecture.
Feel free to make this change in another PR, but would be good to have a resource on how to find this

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/overview.mdx
> +3. Place the binary somewhere on your `PATH` (e.g., `/usr/bin`).
Would be good to add a note about how to inspect PATH (also could be another PR)

2024-10-18 04:54 UTC, RajatPawar commented on src/cli/overview.mdx
> +1. **Generate an API key** in the [Ampersand Dashboard](https://dashboard.withampersand.com/projects/_/api-keys/new).
`https://dashboard.withampersand.com/projects/_/api-keys` works, the `/new` should be removed

2024-10-22 20:33 UTC, laurenzlong commented on src/generate-mint.ts
> +            "cli/command-reference"
can you actually change this to "cli/reference" and also name the file `reference.mdx`?

2024-10-28 20:53 UTC, laurenzlong approved these changes

2024-10-28 20:54 UTC, merged